[build] Move all DIFF* config to configure.in; assume diffutils.
* configure.in (RCS_SET_VN): New AC_DEFUN.
(diffutils): Delete AC_ARG_WITH.
(DIFF_MAYBE): New AC_DEFUN.
(DIFF): Document with AC_VAR_ARG; search list DIFF_MAYBE; check
that specified program behaves like GNU diff, else error out.
(RCS_CHECK_STATUS): New AC_DEFUN.
(DIFF_SUCCESS, DIFF_FAILURE, DIFF_TROUBLE): Use `RCS_CHECK_STATUS'.
(DIFF3_MAYBE): New AC_DEFUN.
(DIFF3): Document with AC_VAR_ARG; search list DIFF3_MAYBE; if
specified program does not behave like GNU diff3, don't bother
looking for one under /usr/lib, etc, just let ed(1) handle it.
(DIFFFLAGS, DIFF_L, DIFF3_BIN): Compute vars
internally; don't let environment influence them.
* README: Update.

* src/Makefile.in (DIFF, DIFF3): Delete vars.
(RCSTEST): Remove DIFF='$(DIFF)'.
(bother.h): Don't output #define:s for `DIFF', `DIFF3'.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -33,6 +33,14 @@ AS_IF([test $2 = $[]$3],[cbool=1],[cbool=0])
 AC_DEFINE_UNQUOTED([$1],[$cbool],[$4])dnl
 ])dnl
 
+AC_DEFUN([RCS_SET_VN],[dnl
+dnl $1 -- shell variable name
+dnl $2 -- value to assign if last command was successful
+rv=$?
+AS_IF([test 0 = $rv],[$1=$2],[$1=no])
+AS_SET_STATUS([$rv])
+])dnl
+
 AC_DEFUN([RCS_MUSTHAVE],[dnl
 dnl $1 -- shell variable name
 dnl $2 -- rest of "could not find ..." error message
@@ -69,21 +77,6 @@ RCS_ABSOLUTE_PROGRAM([SENDMAIL],[mailer],
   [Program used to send mail when a lock is broken.])
 ])
 
-AC_ARG_WITH([diffutils],
- [AS_HELP_STRING([--with-diffutils],
-                 [assume GNU diffutils is similarly installed])],[
-  if test yes = "$withval" ; then
-    : ${DIFF='$(bindir)/diff'}
-    : ${DIFF3=${DIFF}3}
-    : ${DIFF3_BIN=1}
-    : ${DIFFFLAGS=-an}
-    : ${DIFF_FAILURE=1}
-    : ${DIFF_L=1}
-    : ${DIFF_SUCCESS=0}
-    : ${DIFF_TROUBLE=2}
-  fi
-])
-
 # Set up simple `diff' test.
 echo 0 >conftest0
 echo 0 >conftest0c
@@ -91,117 +84,60 @@ echo 1 >conftest1
 { echo d1 1 ; echo a1 1 ; echo 1 ; } >conftestok
 
 # Set DIFF to the name of the `diff' program to be run.
-# On some systems, the RCS-compatible diff program is called `rdiff';
-# use it if it works and `diff' doesn't.
-AC_SUBST(DIFF)
-AC_MSG_CHECKING([diff basename])
-AC_CACHE_VAL(rcs_cv_prog_diff, [
-  rcs_cv_prog_diff=$DIFF
-  case $rcs_cv_prog_diff in
-  '')
-    for i in diff /usr/lib/rdiff rdiff
-    do
-      sh -c "exec $i -n conftest0 conftest1" >conftestout 2>/dev/null
-      case $? in
-      1)
-	if cmp -s conftestok conftestout
-	then rcs_cv_prog_diff=$i; break
-	fi
-	;;
-      esac
-    done
-    ;;
-  esac
+AC_DEFUN([DIFF_MAYBE],[gdiff rdiff diff])
+AC_ARG_VAR([DIFF],[the name of a program that works like diff(1)
+  from GNU diffutils, used to compare files line by line
+  (default is to search the PATH for: ]DIFF_MAYBE[)])
+AC_CHECK_PROGS([DIFF],[DIFF_MAYBE])
+RCS_MUSTHAVE([ac_cv_prog_DIFF],[a diff program (tried: DIFF_MAYBE)])
+AC_CACHE_CHECK([if diff works like GNU diff],[rcs_cv_sane_diff],[
+  rcs_cv_sane_diff=no
+  sh -c "exec $DIFF -n conftest0 conftest1" >conftestout 2>/dev/null
+  test 1 = $? && cmp -s conftestok conftestout
+  RCS_SET_VN([rcs_cv_sane_diff],[yes])
 ])
-DIFF=$rcs_cv_prog_diff
-RCS_MUSTHAVE([DIFF],[RCS-compatible diff])
+RCS_MUSTHAVE([rcs_cv_sane_diff],[a sane diff program ($DIFF unsuitable)])
 RCS_ABSOLUTE_PROGRAM([DIFF],[diff],
   [The diff program from GNU diffutils, or workalike.])
 
 # Set DIFF_SUCCESS, DIFF_FAILURE, DIFF_TROUBLE to diff's exit status
 # when it finds no differences, some differences, or trouble.
-AC_MSG_CHECKING([diff success status])
-AC_CACHE_VAL(rcs_cv_status_diff_success, [
-  rcs_cv_status_diff_success=$DIFF_SUCCESS
-  case $rcs_cv_status_diff_success in
-  '')
-    # We can't use `$DIFF conftest0 conftest0',
-    # since buggy NEXTSTEP 3.0 diff silently yields exit status 2 for this.
-    $DIFF conftest0 conftest0c >/dev/null 2>&1
-    rcs_cv_status_diff_success=$?
-    ;;
-  esac
+AC_DEFUN([RCS_CHECK_STATUS],[
+AS_VAR_PUSHDEF([SDV],[rcs_cv_status_diff_$1])dnl
+AS_VAR_PUSHDEF([CVAR],[DIFF_]m4_toupper($1))dnl
+AC_CACHE_CHECK([diff $1 status],[SDV],[
+  $DIFF $3 $4 >/dev/null 2>&1
+  SDV=$?
 ])
-DIFF_SUCCESS=$rcs_cv_status_diff_success
-AC_MSG_RESULT($DIFF_SUCCESS)
-AC_DEFINE_UNQUOTED([DIFF_SUCCESS],[$DIFF_SUCCESS],
-  [Exit status when diff(1) finds no differences.])
-#
-AC_MSG_CHECKING([diff failure status])
-AC_CACHE_VAL(rcs_cv_status_diff_failure, [
-  rcs_cv_status_diff_failure=$DIFF_FAILURE
-  case $rcs_cv_status_diff_failure in
-  '')
-    $DIFF conftest0 conftest1 >/dev/null 2>&1
-    rcs_cv_status_diff_failure=$?
-    ;;
-  esac
+AC_DEFINE_UNQUOTED([CVAR],[$[]SDV],
+  [Exit status when diff(1) finds $2.])
+AS_VAR_POPDEF([CVAR])dnl
+AS_VAR_POPDEF([SDV])dnl
 ])
-DIFF_FAILURE=$rcs_cv_status_diff_failure
-AC_MSG_RESULT($DIFF_FAILURE)
-AC_DEFINE_UNQUOTED([DIFF_FAILURE],[$DIFF_FAILURE],
-  [Exit status when diff(1) finds some differences.])
-#
-AC_MSG_CHECKING([diff trouble status])
-AC_CACHE_VAL(rcs_cv_status_diff_trouble, [
-  rcs_cv_status_diff_trouble=$DIFF_TROUBLE
-  case $rcs_cv_status_diff_trouble in
-  '')
-    $DIFF conftest0 no/such/file >/dev/null 2>&1
-    rcs_cv_status_diff_trouble=$?
-    ;;
-  esac
-])
-DIFF_TROUBLE=$rcs_cv_status_diff_trouble
-AC_MSG_RESULT($DIFF_TROUBLE)
-AC_DEFINE_UNQUOTED([DIFF_TROUBLE],[$DIFF_TROUBLE],
-  [Exit status when diff(1) finds trouble.])
+
+# We can't use `$DIFF conftest0 conftest0',
+# since buggy NEXTSTEP 3.0 diff silently yields exit status 2 for this.
+RCS_CHECK_STATUS([success],[no differences],[conftest0],[conftest0c])
+RCS_CHECK_STATUS([failure],[some differences],[conftest0],[conftest1])
+RCS_CHECK_STATUS([trouble],[trouble],[conftest0],[no/such/file])
 
 # Set DIFFFLAGS to the options of the `diff' program to be run.
 # Use -an if possible, -n otherwise.
-AC_MSG_CHECKING([diff options for RCS])
-AC_CACHE_VAL(rcs_cv_options_diff, [
-  rcs_cv_options_diff=$DIFFFLAGS
-  case $rcs_cv_options_diff in
-  '')
-    rcs_cv_options_diff=-n
-    $DIFF -an conftest0 conftest1 >conftestout 2>conftestout2
-    case $? in
-    1)
-      if cmp -s conftestok conftestout && test ! -s conftestout2
-      then rcs_cv_options_diff=-an
-      fi
-      ;;
-    esac
-    ;;
-  esac
+AC_CACHE_CHECK([diff options for RCS],[rcs_cv_options_diff],[
+  $DIFF -an conftest0 conftest1 >conftestout 2>conftestout2
+AS_IF([test 1 = $? &&
+       cmp -s conftestok conftestout &&
+       test ! -s conftestout2],
+      [rcs_cv_options_diff=-an],
+      [rcs_cv_options_diff=-n])
 ])
-DIFFFLAGS=$rcs_cv_options_diff
-AC_MSG_RESULT($DIFFFLAGS)
-AC_DEFINE_UNQUOTED([DIFFFLAGS],["$DIFFFLAGS"],
+AC_DEFINE_UNQUOTED([DIFFFLAGS],["$rcs_cv_options_diff"],
   [Options of the `diff' program to be run.])
 
 # Set DIFF_L to 1 if diff understands the L option, 0 otherwise.
-AC_MSG_CHECKING([diff -L])
-AC_CACHE_VAL(rcs_cv_options_diff_l, [
-  rcs_cv_options_diff_l=$DIFF_L
-  case $rcs_cv_options_diff_l in
-  '')
-    rcs_cv_options_diff_l=0
-    $DIFF -c -L 0 -L 1 conftest0 conftest1 >conftestout 2>/dev/null
-    case $? in
-    1)
-      if cmp -s - conftestout <<'EOF'
+AC_CACHE_CHECK([if diff understands option -L],[rcs_cv_options_diff_l],[
+  $DIFF -c -L 0 -L 1 conftest0 conftest1 >conftestout 2>/dev/null
+  test 1 = $? && cmp -s - conftestout <<'EOF'
 *** 0
 --- 1
 ***************
@@ -210,97 +146,34 @@ AC_CACHE_VAL(rcs_cv_options_diff_l, [
 --- 1 ----
 ! 1
 EOF
-      then rcs_cv_options_diff_l=1
-      fi
-      ;;
-    esac
-    ;;
-  esac
+  RCS_SET_VN([rcs_cv_options_diff_l],[yes])
 ])
-DIFF_L=$rcs_cv_options_diff_l
-case $DIFF_L in
-1) AC_MSG_RESULT(yes);;
-*) AC_MSG_RESULT(no);;
-esac
-AC_DEFINE_UNQUOTED([DIFF_L],[$DIFF_L],
-  [Does diff(3) understand -L?])
+RCS_CBOOL([DIFF_L],[yes],[rcs_cv_options_diff_l],
+  [Does diff(1) understand -L?])
 
 # Set DIFF3 to the name of the diff3 program.
-# In some systems (e.g. BSD/OS 2.0), diffutils diff3 lives in /usr/libexec.
-diff3PATH=$PATH:/usr/libexec
-AC_SUBST(DIFF3)
-AC_MSG_CHECKING([diff3 -m])
-AC_CACHE_VAL(rcs_cv_prog_diff3_bin, [
-  rcs_cv_prog_diff3_bin=$DIFF3
-  case $rcs_cv_prog_diff3_bin in
-  '')
-    PATH=$diff3PATH sh -c "exec diff3 -E -m -L 0 -L 1 -L 2 conftest0 conftest1 /dev/null" >conftestout 2>/dev/null
-    case $? in
-    1)
-      if cmp -s - conftestout <<'EOF'
+AC_DEFUN([DIFF3_MAYBE],[gdiff3 diff3])
+AC_ARG_VAR([DIFF3],[the name of a program that works like diff3(1)
+  from GNU diffutils, used to compare three files line by line
+  (default is to search the PATH for: ]DIFF3_MAYBE[)])
+AC_CHECK_PROGS([DIFF3],[DIFF3_MAYBE])
+RCS_MUSTHAVE([ac_cv_prog_DIFF3],[a diff3 program (tried: DIFF3_MAYBE)])
+RCS_ABSOLUTE_PROGRAM([DIFF3],[diff3],
+  [A diff3 program, possibly slightly insane wrt GNU diff3.])
+
+AC_CACHE_CHECK([if diff3 works like GNU diff3],[rcs_cv_sane_diff3],[
+  rcs_cv_sane_diff3=no
+  sh -c "exec $DIFF3 -E -m -L 0 -L 1 -L 2 conftest0 conftest1 /dev/null" >conftestout 2>/dev/null
+  test 1 = $? && cmp -s - conftestout <<'EOF'
 <<<<<<< 0
 0
 =======
 >>>>>>> 2
 EOF
-      then rcs_cv_prog_diff3_bin=diff3
-      fi
-      ;;
-    esac
-  ;;
-  esac
+  RCS_SET_VN([rcs_cv_sane_diff3],[yes])
 ])
-case $rcs_cv_prog_diff3_bin in
-?*)
-  AC_MSG_RESULT(yes)
-  ac_save_path=$PATH
-  PATH=$diff3PATH
-  DIFF3=$rcs_cv_prog_diff3_bin
-RCS_ABSOLUTE_PROGRAM([DIFF3],[diff3],
-  [A diff3 program, possibly slightly insane wrt GNU diff3.])
-  PATH=$ac_save_path
-  ;;
-'')
-  AC_MSG_RESULT(no)
-  AC_MSG_CHECKING([diff3 library program])
-  dnl We can't use AC_PATH_PROG since we don't want to inspect /bin,
-  dnl and AC_PATH_PROG uses `test'.
-  AC_CACHE_VAL(rcs_cv_path_diff3_lib, [
-    $DIFF conftest0 conftest1 >conftest01
-    $DIFF /dev/null conftest1 >conftestn1
-    for i in /usr/*lib*/*diff3*; do
-      sh -c "exec $i -E conftest01 conftestn1 conftest0 /dev/null conftest1" >conftestout 2>/dev/null
-      # The exit status is arbitrary!  Test the output a bit.
-      if
-	grep '^<<* *conftest0$' conftestout >/dev/null 2>&1 &&
-	grep '^>>* *conftest1$' conftestout >/dev/null 2>&1 &&
-	grep '^0a$' conftestout >/dev/null 2>&1
-      then
-	rcs_cv_path_diff3_lib=$i
-	break
-      fi
-    done
-  ])
-  DIFF3=$rcs_cv_path_diff3_lib
-  RCS_MUSTHAVE([DIFF3],[a working diff3 library program])
-  AC_MSG_RESULT($DIFF3)
-  ;;
-esac
-
-case $DIFF3_BIN in
-'')
-  case $rcs_cv_prog_diff3_bin in
-  '') DIFF3_BIN=0;;
-  ?*) DIFF3_BIN=1;;
-  esac
-  ;;
-esac
-AC_DEFINE_UNQUOTED([DIFF3_BIN],[$DIFF3_BIN],
-  [Is the diff3 program the user-visible GNU diff3?])
-
-# Clean up simple `diff' test.
-rm -f conftest*
-
+RCS_CBOOL([DIFF3_BIN],[yes],[rcs_cv_sane_diff3],
+  [Does diff3 work like GNU binutils diff3?])
 ED=ed
 RCS_ABSOLUTE_PROGRAM([ED],[original ed],
   [The singular ed(1), necessary only if diff3 is not completely sane.])
